// packages/taro-components/h5/vue/components/picker.vue
<template>
  <taro-picker-core
    :mode='mode'
    :disabled='disabled'
    :range.prop="range"
    :range-key="rangeKey"
    :start="start"
    :end="end"
    :fields="fields"
    :name="name"
    @change="onChange"
    @columnchange="onColumnChange"
    @cancel="onCancel"
  >
    <slot />
  </taro-picker-core>
</template>

<script>
export default {
  name: 'taro-picker',
  props: {
    'mode': String,
    'disabled': Boolean,
    'range': Array,
    'rangeKey': String,
    'value': [Number, String, Array],
    'start': String,
    'end': String,
    'fields': String,
    'name': String
  },
  mounted () {
    this.$el.value = this.value
  },
  watch: {
    value (newVal) {
      this.$el.value = newVal
    }
  },
  methods: {
    onChange (e) {
      this.$emit('change', e)
    },
    onColumnChange (e) {
      this.$emit('columnchange', e)
    },
    onCancel (e) {
      this.$emit('cancel', e)
    }
  }
}
</script>

// packages/taro-components-rn/src/components/Picker/index.tsx
/**
 * All:
 *   ✔ value
 *   ✔ onChange
 *   ✔ onCancel
 * Selector:
 *   ✔ range
 *   ✔ rangeKey
 *   ✔ disabled
 * MultiSelector:
 *   ✔ range
 *   ✔ rangeKey
 *   ✔ disabled
 *   ✔ onColumnChange
 * Time:
 *   ✔ start
 *   ✔ end
 *   ✔ disabled
 * Date:
 *   ✔ start
 *   ✔ end
 *   ✘ fields
 *   ✔ disabled
 * Region:
 *   ✔ customItem
 *   ✔ disabled
 *
 * @hint Picker 里面嵌套的子组件要支持绑定 onPress 事件才能弹出选择框
 */

import * as React from 'react'

import Selector from './selector'
import MultiSelector from './multiSelector'
import TimeSelector from './time'
import DateSelector from './date'
import RegionSelector from './region'

export default class _Picker extends React.Component<any> {
  static defaultProps = {
    mode: 'selector',
  }

  render () {
    const {
      mode,
    } = this.props

    if (mode === 'selector') {
      return <Selector {...this.props} />
    } else if (mode === 'multiSelector') {
      return <MultiSelector {...this.props} />
    } else if (mode === 'time') {
      return <TimeSelector {...this.props} />
    } else if (mode === 'date') {
      return <DateSelector {...this.props} />
    } else if (mode === 'region') {
      return <RegionSelector {...this.props} />
    } else {
      return null
    }
  }
}
