// packages/taro-components/src/components/image/image.tsx
import { Component, Prop, h, ComponentInterface, Host, State, Event, EventEmitter, Element } from '@stencil/core'
import classNames from 'classnames'

require('intersection-observer')

@Component({
  tag: 'taro-image',
  styleUrl: './style/index.scss'
})
export class Image implements ComponentInterface {
  @Prop() src: string
  @Prop() mode = 'scaleToFill'
  @Prop() lazyLoad = false
  @State() isLoaded = false

  @Event({
    eventName: 'load'
  }) onLoad: EventEmitter

  @Event({
    eventName: 'error'
  }) onError: EventEmitter

  private imgRef: HTMLImageElement

  @Element() el: HTMLElement

  componentDidLoad () {
    if (this.lazyLoad) {
      const lazyImg = new IntersectionObserver((entries) => {
        // 异步 api 关系
        if (entries[entries.length - 1].isIntersecting) {
          this.isLoaded = true
          lazyImg.unobserve(this.imgRef)
          this.imgRef.src = this.src
        }
      }, {
        rootMargin: '300px 0px'
      })
    }
  }

  imageOnLoad () {
    this.onLoad.emit({
      width: this.imgRef.width,
      height: this.imgRef.height
    })
  }

  imageOnError () {
    this.onError.emit()
  }

  render () {
    const cls = classNames(
      'taro-img',
      {
        'taro-img__widthfix': this.mode === 'widthFix'
      }
    )
    const imgCls = classNames(
      'taro-img__mode-' +
        (this.mode || 'scaleToFill').toLowerCase().replace(/\s/g, '')
    )
    return (
      <Host class={cls}>
        {this.lazyLoad ? (
          <img
            ref={img => (this.imgRef = img!)}
            class={imgCls}
            data-src={this.src}
            onLoad={this.imageOnLoad}
            onError={this.imageOnError}
          />
        ) : (
          <img
            ref={img => (this.imgRef = img!)}
            class={imgCls}
            src={this.src}
            onLoad={this.imageOnLoad}
            onError={this.imageOnError}
          />
        )}
      </Host>
    )
  }
}

// packages/taro-components-react/src/components/image/index.tsx
import 'weui'
import './style/index.css'

import classNames from 'classnames'
import React from 'react'

require('intersection-observer')

interface IProps extends React.HTMLAttributes<HTMLDivElement> {
  src: string
  mode: string
  onError: () => void
  onLoad: (e) => void
  lazyLoad?: boolean
  imgProps?: Record<string, any>
}

class Image extends React.Component<IProps> {
  constructor (props) {
    super(props)
    this.state = {
      isLoaded: false
    }
    this.imageOnLoad = this.imageOnLoad.bind(this)
    // this.observer = {}
  }

  observer: any = {}
  imgRef: any = null

  componentDidMount () {
    if (this.props.lazyLoad) {
      this.observer = new IntersectionObserver(
        entries => {
          // 异步 api 关系
          if (entries[entries.length - 1].isIntersecting) {
            this.setState({ isLoaded: true }, () => {
              // findDOMNode(this).children[0].src = this.props.src
              this.imgRef.src = this.props.src
            })
          }
        },
        {
          rootMargin: '300px 0px'
        }
      )
      this.observer.observe(this.imgRef)
    }
  }

  componentWillUnmount () {
    this.observer.disconnect && this.observer.disconnect()
  }

  imageOnLoad (e) {
    const { onLoad } = this.props
    Object.defineProperty(e, 'detail', {
      enumerable: true,
      writable: true,
      value: {
        width: e.target.width,
        height: e.target.height
      }
    })

    onLoad && onLoad(e)
  }

  render () {
    const {
      className,
      style = {},
      src,
      mode,
      onError,
      lazyLoad,
      imgProps,
      ...reset
    } = this.props
    const cls = classNames(
      'taro-img',
      {
        'taro-img__widthfix': mode === 'widthFix'
      },
      className
    )
    const imgCls = classNames(
      'taro-xxx-img__mode-' +
        (mode || 'scaleToFill').toLowerCase().replace(/\s/g, '')
    )

    return (
      <div className={cls} style={style} {...reset}>
        {lazyLoad ? (
          <img
            ref={img => (this.imgRef = img)}
            className={imgCls}
            data-src={src}
            onLoad={this.imageOnLoad}
            onError={onError}
            {...imgProps}
          />
        ) : (
          <img
            ref={img => (this.imgRef = img)}
            className={imgCls}
            src={src}
            onLoad={this.imageOnLoad}
            onError={onError}
            {...imgProps}
          />
        )}
      </div>
    )
  }
}

export default Image
