// packages/taro-components-react/src/components/scroll-view/index.tsx
import 'weui'
import React from 'react'
// import omit from 'omit.js'
import classNames from 'classnames'
import './style/index.css'

function easeOutScroll (from = 0, to = 0, callback) {
  if (from === to || typeof from !== 'number') {
    return
  }
  const change = to - from
  const dur = 500
  const sTime = +new Date()
  function linear (t, b, c, d) {
    return c * t / d + b
  }
  const isLarger = to >= from

  function step () {
    from = linear(+new Date() - sTime, from, change, dur)
    if ((isLarger && from >= to) || (!isLarger && to >= from)) {
      callback(to)
      return
    }
    callback(from)
    requestAnimationFrame(step)
  }
  step()
}
function throttle (fn, delay) {
  let timer: any = null
  return function (...arrs) {
    clearTimeout(timer)
    timer = setTimeout(function () {
      fn(...arrs)
    }, delay)
  }
}
function scrollIntoView (id) {
  document.querySelector(`#${id}`)?.scrollIntoView({
    behavior: 'smooth',
    block: 'center',
    inline: 'start'
  })
}
function scrollVertical (top, isAnimation) {
  if (isAnimation) {
    easeOutScroll(this._scrollTop, top, pos => {
      if (this.container) this.container.scrollTop = pos
    })
  } else {
    if (this.container) this.container.scrollTop = top
  }
  this._scrollTop = top
}
function scrollHorizontal (left, isAnimation) {
  if (isAnimation) {
    easeOutScroll(this._scrollLeft, left, pos => {
      if (this.container) this.container.scrollLeft = pos
    })
  } else {
    if (this.container) this.container.scrollLeft = left
  }
  this._scrollLeft = left
}

interface IProps {
  className?: string
  style?: Record<string, string>
  scrollX: boolean
  scrollY: boolean
  upperThreshold: number
  lowerThreshold: number
  scrollTop: number
  scrollLeft: number
  scrollIntoView?: string
  scrollWithAnimation: boolean
  enableBackToTop ?: boolean
  onScrollToUpper: (e: React.SyntheticEvent<HTMLDivElement, Event>) => void
  onScrollToLower: (e: React.SyntheticEvent<HTMLDivElement, Event>) => void
  onScroll: (e: React.SyntheticEvent<HTMLDivElement, Event>) => void
  onTouchMove: (e: React.SyntheticEvent<HTMLDivElement, Event>) => void

}

class ScrollView extends React.Component<IProps> {
  _scrollTop: any = null
  _scrollLeft: any = null
  container: any = null

  onTouchMove = e => {
    e.stopPropagation()
  }

  componentDidMount () {
    this.handleScroll(this.props, true)
  }

  UNSAFE_componentWillReceiveProps (nextProps) {
    this.handleScroll(nextProps)
  }

  handleScroll (props, isInit = false) {
    // scrollIntoView
    if (
      props.scrollIntoView &&
      typeof props.scrollIntoView === 'string' &&
      document &&
      document.querySelector &&
      document.querySelector(`#${props.scrollIntoView}`)
    ) {
      if (isInit) {
        setTimeout(() => scrollIntoView(props.scrollIntoView), 500)
      } else {
        scrollIntoView(props.scrollIntoView)
      }
    } else {
      const isAnimation = 'scrollWithAnimation' in props
      // Y 轴滚动
      if (
        props.scrollY &&
        typeof props.scrollTop === 'number' &&
        props.scrollTop !== this._scrollTop
      ) {
        if (isInit) {
          setTimeout(() => scrollVertical.bind(this)(props.scrollTop, isAnimation), 10)
        } else {
          scrollVertical.bind(this)(props.scrollTop, isAnimation)
        }
      }
      // X 轴滚动
      if (
        props.scrollX &&
        typeof props.scrollLeft === 'number' &&
        props.scrollLeft !== this._scrollLeft
      ) {
        if (isInit) {
          setTimeout(() => scrollHorizontal.bind(this)(props.scrollLeft, isAnimation), 10)
        } else {
          scrollHorizontal.bind(this)(props.scrollLeft, isAnimation)
        }
      }
    }
  }

  render () {
    const {
      className,
      style = {},
      onScroll,
      onScrollToUpper,
      onScrollToLower,
      onTouchMove,
      scrollX,
      scrollY
    } = this.props
    let { upperThreshold = 50, lowerThreshold = 50 } = this.props
    const cls = classNames(
      'taro-scroll',
      {
        'taro-scroll-view__scroll-x': scrollX,
        'taro-scroll-view__scroll-y': scrollY
      },
      className
    )
    upperThreshold = Number(upperThreshold)
    lowerThreshold = Number(lowerThreshold)
    const uperAndLower = (e) => {
      if (!this.container) return
      const {
        offsetWidth,
        offsetHeight,
        scrollLeft,
        scrollTop,
        scrollHeight,
        scrollWidth
      } = this.container
      if (
        onScrollToLower &&
        ((this.props.scrollY &&
          offsetHeight + scrollTop + lowerThreshold >= scrollHeight) ||
          (this.props.scrollX &&
            offsetWidth + scrollLeft + lowerThreshold >= scrollWidth))
      ) {
        onScrollToLower(e)
      }
      if (
        onScrollToUpper &&
        ((this.props.scrollY && scrollTop <= upperThreshold) ||
          (this.props.scrollX && scrollLeft <= upperThreshold))
      ) {
        onScrollToUpper(e)
      }
    }
    const uperAndLowerThrottle = throttle(uperAndLower, 200)
    const _onScroll = e => {
      const {
        scrollLeft,
        scrollTop,
        scrollHeight,
        scrollWidth
      } = this.container
      this._scrollLeft = scrollLeft
      this._scrollTop = scrollTop
      Object.defineProperty(e, 'detail', {
        enumerable: true,
        writable: true,
        value: {
          scrollLeft,
          scrollTop,
          scrollHeight,
          scrollWidth
        }
      })
      uperAndLowerThrottle(e)
      onScroll && onScroll(e)
    }
    const _onTouchMove = e => {
      onTouchMove ? onTouchMove(e) : this.onTouchMove(e)
    }
    return (
      <div
        ref={container => {
          this.container = container
        }}
        style={style}
        className={cls}
        onScroll={_onScroll}
        onTouchMove={
          _onTouchMove
        }
      >
        {this.props.children}
      </div>
    )
  }
}

export default ScrollView

// packages/taro-components/src/components/scroll-view/scroll-view.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Component, h, ComponentInterface, Prop, Event, EventEmitter, Watch, Element, Host } from '@stencil/core'
import classNames from 'classnames'

function easeOutScroll (from: number, to: number, callback) {
  if (from === to || typeof from !== 'number') {
    return
  }

  const change = to - from
  const dur = 500
  const sTime = Date.now()
  const isLarger = to >= from

  function linear (t: number, b: number, c: number, d: number): number {
    return c * t / d + b
  }

  function step () {
    from = linear(Date.now() - sTime, from, change, dur)
    if ((isLarger && from >= to) || (!isLarger && to >= from)) {
      callback(to)
      return
    }
    callback(from)
    requestAnimationFrame(step)
  }

  step()
}

function debounce (fn, delay: number) {
  let timer: NodeJS.Timeout

  return function (...arrs) {
    clearTimeout(timer)
    timer = setTimeout(function () {
      fn(...arrs)
    }, delay)
  }
}

@Component({
  tag: 'taro-scroll-view-core',
  styleUrl: './style/index.scss'
})
export class ScrollView implements ComponentInterface {
  private _scrollLeft: number
  private _scrollTop: number

  @Element() el: HTMLElement

  @Prop() scrollX = false
  @Prop() scrollY = false
  @Prop() upperThreshold: number | string = 50
  @Prop() lowerThreshold: number | string = 50
  @Prop({ attribute: 'scroll-top' }) mpScrollTop: number | string
  @Prop({ attribute: 'scroll-left' }) mpScrollLeft: number | string
  @Prop({ attribute: 'scroll-into-view' }) mpScrollIntoView: string
  @Prop() scrollWithAnimation = false

  @Event({
    eventName: 'scroll'
  })
  onScroll: EventEmitter

  @Event({
    eventName: 'scrolltoupper'
  })
  onScrollToUpper: EventEmitter

  @Event({
    eventName: 'scrolltolower'
  })
  onScrollToLower: EventEmitter

  @Watch('mpScrollLeft')
  watchScrollLeft (newVal) {
    const scrollLeft = Number(newVal)
    if (this.scrollX && !isNaN(scrollLeft)) {
      if (this.scrollWithAnimation) {
        easeOutScroll(this._scrollLeft, scrollLeft, pos => (this.el.scrollLeft = pos))
      } else {
        this.el.scrollLeft = scrollLeft
      }
      this._scrollLeft = scrollLeft
    }
  }

  @Watch('mpScrollTop')
  watchScrollTop (newVal) {
    const scrollTop = Number(newVal)
    if (this.scrollY && !isNaN(scrollTop)) {
      if (this.scrollWithAnimation) {
        easeOutScroll(this._scrollTop, scrollTop, pos => (this.el.scrollTop = pos))
      } else {
        this.el.scrollTop = scrollTop
      }
      this._scrollTop = scrollTop
    }
  }

  @Watch('mpScrollIntoView')
  watchScrollIntoView (newVal) {
    if (typeof newVal === 'string' && newVal) {
      document.querySelector(`#${newVal}`)?.scrollIntoView({
        behavior: 'smooth',
        block: 'center',
        inline: 'start'
      })
    }
  }

  componentDidLoad () {
    const {
      scrollY,
      scrollX,
      scrollWithAnimation
    } = this

    const scrollTop = Number(this.mpScrollTop)
    const scrollLeft = Number(this.mpScrollLeft)

    if (scrollY && !isNaN(scrollTop)) {
      if (scrollWithAnimation) {
        easeOutScroll(0, scrollTop, pos => (this.el.scrollTop = pos))
      } else {
        this.el.scrollTop = scrollTop
      }
      this._scrollTop = scrollTop
    }

    if (scrollX && !isNaN(scrollLeft)) {
      if (scrollWithAnimation) {
        easeOutScroll(0, scrollLeft, pos => (this.el.scrollLeft = pos))
      } else {
        this.el.scrollLeft = scrollLeft
      }
      this._scrollLeft = scrollLeft
    }
  }

  handleScroll = (e) => {
    if (e instanceof CustomEvent) return

    const {
      scrollLeft,
      scrollTop,
      scrollHeight,
      scrollWidth
    } = this.el
    this._scrollLeft = scrollLeft
    this._scrollTop = scrollTop

    this.uperAndLower()

    this.onScroll.emit({
      scrollLeft,
      scrollTop,
      scrollHeight,
      scrollWidth
    })
  }

  uperAndLower = debounce(() => {
    const {
      offsetWidth,
      offsetHeight,
      scrollLeft,
      scrollTop,
      scrollHeight,
      scrollWidth
    } = this.el

    const lowerThreshold = Number(this.lowerThreshold)
    const upperThreshold = Number(this.upperThreshold)

    if (
      !isNaN(lowerThreshold) &&
      ((this.scrollY && offsetHeight + scrollTop + lowerThreshold >= scrollHeight) ||
      (this.scrollX && offsetWidth + scrollLeft + lowerThreshold >= scrollWidth))
    ) {
      this.onScrollToLower.emit({
        direction: this.scrollX ? 'right' : (this.scrollY ? 'bottom' : '')
      })
    }

    if (
      !isNaN(upperThreshold) &&
      ((this.scrollY && scrollTop <= upperThreshold) ||
      (this.scrollX && scrollLeft <= upperThreshold))
    ) {
      this.onScrollToUpper.emit({
        direction: this.scrollX ? 'left' : (this.scrollY ? 'top' : '')
      })
    }
  }, 200)

  render () {
    const {
      scrollX,
      scrollY
    } = this

    const cls = classNames({
      'taro-scroll-view__scroll-x': scrollX,
      'taro-scroll-view__scroll-y': scrollY
    })
    return (
      <Host
        class={cls}
        onScroll={this.handleScroll}
      >
        <slot />
      </Host>
    )
  }
}
