// packages/taro-components-rn/src/components/Video/index.tsx
import React, { Component } from 'react'
import { formatTime } from './utils'
import { VideoProps } from '@tarojs/components/types/Video'
import {
  AVPlaybackStatus,
  Video,
  VideoFullscreenUpdateEvent,
  VideoReadyForDisplayEvent,
} from 'expo-av'
import Styles from './style'
import View from '../View'
import Text from '../Text'
import Image from '../Image'
import { onFullscreenChangeEventDetail } from './PropsType'
/**
 * @typedef {Object} Danmu
 * @property {string} text 弹幕文字
 * @property {string} color 弹幕颜色
 * @property {number} [time] 弹幕时间
 */

/**
 * Video组件参数
 * @typedef {Object} VideoProps
 * @property {string} src 要播放视频的资源地址
 * @property {boolean} [autoPauseIfNavigate=true] 当跳转到其它小程序页面时，是否自动暂停本页面的视频
 * @property {boolean} [autoPauseIfOpenNative=true] 当跳转到其它微信原生页面时，是否自动暂停本页面的视频
 * @property {boolean} [autoplay=false] 是否自动播放
 * @property {boolean} [controls=true] 是否显示默认播放控件（播放/暂停按钮、播放进度、时间）
 * @property {boolean} [danmuBtn=false] 是否显示弹幕按钮，只在初始化时有效，不能动态变更
 * @property {Array.<Danmu>} [danmuList=[]] 弹幕列表
 * @property {boolean} [enableDanmu=false] 是否展示弹幕，只在初始化时有效，不能动态变更
 * @property {boolean} [enablePlayGesture=false] 是否开启播放手势，即双击切换播放/暂停
 * @property {boolean} [enableProgressGesture=true] 是否开启控制进度的手势
 * @property {number} [initialTime=0] 指定视频初始播放位置
 * @property {boolean} [loop=false] 是否循环播放
 * @property {boolean} [muted=false] 是否静音播放
 * @property {string} [objectFit=contain] 当视频大小与 video 容器大小不一致时，视频的表现形式
 * @property {string} [playBtnPosition=bottom] 播放按钮的位置
 * @property {boolean} [showCenterPlayBtn=true] 是否显示视频中间的播放按钮
 * @property {boolean} [showFullscreenBtn=true] 是否显示全屏按钮
 * @property {boolean} [showMuteBtn=false] 是否显示静音按钮
 * @property {boolean} [showPlayBtn=true] 是否显示视频底部控制栏的播放按钮
 * @property {boolean} [showProgress=true] 若不设置，宽度大于240时才会显示
 * @property {boolean} [vslideGesture=false] 在非全屏模式下，是否开启亮度与音量调节手势（同 pageGesture）
 * @property {boolean} [vslideGestureInFullscreen=true] 在全屏模式下，是否开启亮度与音量调节手势
 * @property {number} [direction]  设置全屏时视频的方向，不指定则根据宽高比自动判断
 * @property {number} [duration]  指定视频时长
 * @property {string} [poster]  视频封面的图片网络资源地址。若 controls 属性值为 false 则设置 poster 无效
 * @property {string} [title]  视频的标题，全屏时在顶部展示
 * @property {Function} [onPlay] 当开始/继续播放时触发play事件
 * @property {Function} [onPause] 当暂停播放时触发 pause 事件
 * @property {Function} [onEnded] 当播放到末尾时触发 ended 事件
 * @property {Function} [onTimeUpdate] 播放进度变化时触发，event.detail = {currentTime, duration} 。触发频率 250ms 一次
 * @property {Function} [onFullscreenChange] 视频进入和退出全屏时触发，event.detail = {fullScreen, direction}，direction 有效值为 vertical 或 horizontal
 * @property {Function} [onWaiting] 视频出现缓冲时触发
 * @property {Function} [onError] 视频播放出错时触发
 * @property {Function} [onProgress] 加载进度变化时触发，只支持一段加载。event.detail = {buffered}，百分比
 */

const ObjectFit = {
  contain: Video.RESIZE_MODE_CONTAIN,
  fill: Video.RESIZE_MODE_STRETCH,
  cover: Video.RESIZE_MODE_COVER,
}

declare const global: any

global._taroVideoMap = {}

interface Props extends VideoProps {
  onLoad: () => void;
}

class _Video extends Component<Props, any> {
  /** @type {VideoProps} */
  static defaultProps: Props = {
    id: '',
    src: '',
    autoPauseIfNavigate: true,
    autoPauseIfOpenNative: true,
    autoplay: false,
    controls: true,
    danmuBtn: false,
    danmuList: [],
    enableDanmu: false,
    enablePlayGesture: false,
    enableProgressGesture: true,
    initialTime: 0,
    loop: false,
    muted: false,
    objectFit: 'contain',
    playBtnPosition: 'bottom',
    showCenterPlayBtn: true,
    showFullscreenBtn: true,
    showMuteBtn: false,
    showPlayBtn: true,
    showProgress: true,
    vslideGesture: false,
    vslideGestureInFullscreen: true,
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    onLoad: () => {},
  };

  /** @type {HTMLVideoElement} */
  videoRef: Video;

  /** @type {number} */
  currentTime = 0;

  progressDimentions = {
    left: 0,
    right: 0,
    width: 0,
  };

  getVideoRef: (ref: any) => void;
  isDraggingProgress: any;
  duration: any;
  toastVolumeRef: any;
  toastVolumeBarRef: any;
  toastProgressTitleRef: any;
  toastProgressRef: any;
  getControlsRef: (ref: any) => void;
  getDanmuRef: (ref: any) => void;
  getToastProgressRef: (ref: any) => void;
  getToastProgressTitleRef: (ref: any) => void;
  getToastVolumeRef: (ref: any) => void;
  getToastVolumeBarRef: (ref: any) => void;
  unbindTouchEvents: () => void;

  constructor({ props, context }: { props: Props; context: any }) {
    super(props, context)
    const stateObj = this.props
    this.videoRef = (React.createRef() as unknown) as Video
    this.state = Object.assign(
      {
        duration: null,
        isPlaying: false,
        isFirst: true,
        enableDanmu: false,
        isFullScreen: false,
        isMute: false,
      },
      stateObj
    )
  }

  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
  onEnded = (e: any): void => {
    this.setState({
      // isFirst: true,
      isEnded: true,
    })
    if (!this.props.loop) this.pause()
    this.props.onEnded && this.props.onEnded(e)
  };

  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
  onPlay = (e: any): void => {
    this.props.onPlay && this.props.onPlay(e)
    if (!this.state.isPlaying) {
      this.play()
    }
  };

  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
  onPause = (e: any): void => {
    this.props.onPause && this.props.onPause(e)
    if (this.state.isPlaying) {
      this.setState({
        isPlaying: false,
      })
    }
  };

  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
  onError = (e: string): void => {
    if (this.props.onError) {
      const error: any = Object.defineProperty({}, 'detail', {
        enumerable: true,
        value: { errMsg: e },
      })
      this.props.onError(error)
    }
  };

  onLoad = (status: AVPlaybackStatus): void => {
    const { durationMillis = 0 }: any = status
    this.setState({
      duration: durationMillis,
    })
    this.props.onLoad && this.props.onLoad()
  };

  clickPlayBtn = ():void => {
    const { isEnded } = this.state
    isEnded && this.seek(0)
    this.videoRef && this.videoRef.playAsync()
    this.setState({
      shouldPlay: true,
      isFirst: false,
    })
  }

  play = (): void => {
    const { isEnded } = this.state
    isEnded && this.seek(0)
    this.videoRef.playAsync()
    this.setState({
      shouldPlay: true,
      isPlaying: true,
      isFirst: false,
    })
  };

  pause = (): void => {
    this.setState({
      isPlaying: false,
      shouldPlay: false,
    })
  };

  stop = (): void => {
    this.pause()
    this.seek(0)
    this.setState({
      isPlaying: false,
    })
  };

  seek = (position: number): void => {
    this.videoRef.setStatusAsync({
      positionMillis: position,
    })
  };

  showStatusBar = (): void => {
    console.error('暂不支持 videoContext.showStatusBar')
  };

  hideStatusBar = (): void => {
    console.error('暂不支持 videoContext.hideStatusBar')
  };

  requestFullScreen = (): void => {
    this.videoRef.presentFullscreenPlayer()
  };

  exitFullScreen = (): void => {
    this.videoRef.dismissFullscreenPlayer()
  };

  componentDidMount(): void {
    const getRef = (refName: string) => {
      const { id } = this.props
      return (ref: any) => {
        if (!ref) return
        this[refName] = ref
        id && (global._taroVideoMap[id] = ref)
      }
    }
    this.getVideoRef = getRef('videoRef')
  }

  static getDerivedStateFromProps(nProps: VideoProps): VideoProps {
    return nProps
  }

  onLoadedMetaData = (event: VideoReadyForDisplayEvent): void => {
    const { naturalSize, status } = event
    // @ts-ignore
    status.duration = status.durationMillis
    // @ts-ignore
    this.props.onLoadedMetaData && this.props.onLoadedMetaData({ detail: { ...naturalSize, ...status } })
  };

  onFullscreenChange = (event: VideoFullscreenUpdateEvent): void => {
    const { fullscreenUpdate, status } = event
    const fullScreen: boolean = fullscreenUpdate === Video.FULLSCREEN_UPDATE_PLAYER_WILL_PRESENT || fullscreenUpdate === Video.FULLSCREEN_UPDATE_PLAYER_DID_PRESENT
    const detail: onFullscreenChangeEventDetail = {
      fullScreen: fullscreenUpdate === Video.FULLSCREEN_UPDATE_PLAYER_WILL_PRESENT || fullscreenUpdate === Video.FULLSCREEN_UPDATE_PLAYER_DID_PRESENT,
      fullscreenUpdate,
      direction: 1,
      ...status,
    }
    if (this.state.isFullScreen !== fullScreen) {
      this.setState({
        isFullScreen: fullScreen,
      }, () => {
        // @ts-ignore
        this.props.onFullscreenChange && this.props.onFullscreenChange({ detail })
      })
    }
  };

  onPlaybackStatusUpdate = (event: AVPlaybackStatus): void => {
    // @ts-ignore
    this.props.onTimeUpdate && this.props.onTimeUpdate(event)
    // @ts-ignore
    const { didJustFinish, isPlaying } = event
    if (didJustFinish) {
      this.onEnded(event)
    }

    if (isPlaying !== this.state.isPlaying) {
      this.setState(
        {
          isPlaying,
          isFirst: isPlaying ? false : this.state.isFirst
        },
        () => {
          isPlaying && this.onPlay(event)
          !isPlaying && !this.state.isFirst && this.onPause(event)
        }
      )
    }
  };

  render(): JSX.Element {
    const {
      src,
      autoplay,
      style,
      initialTime,
      loop,
      muted,
      objectFit = 'contain',
      poster,
      controls,
      showCenterPlayBtn,
    } = this.props
    const { isFullScreen, shouldPlay } = this.state
    const duration = formatTime(
      this.props.duration || this.state.duration || null
    )
    const videoProps = {
      source: { uri: src },
      shouldPlay: shouldPlay || autoplay,
      posterSource: controls ? { uri: poster } : undefined,
      usePoster: !!controls,
      isLooping: loop,
      isMuted: muted,
      positionMillis: initialTime,
      style: Object.assign({ width: '100%', height: '100%' }, style as Record<string, unknown>),
      ref: this.getVideoRef,
      resizeMode: ObjectFit[objectFit],
      useNativeControls: controls,
      onError: this.onError,
      onLoad: this.onLoad,
      onReadyForDisplay: this.onLoadedMetaData,
      onFullscreenUpdate: this.onFullscreenChange,
      onPlaybackStatusUpdate: this.onPlaybackStatusUpdate,
    }

    // 第一次不显示又无法自动播放
    const showPlayBtn = this.state.isFirst ? true : showCenterPlayBtn

    const videoNode = (
      <View
        style={[
          Styles['taro-video-container'],
          isFullScreen && Styles['taro-video-type-fullscreen'],
        ]}
      >
        <Video {...videoProps} />
        {showPlayBtn && !this.state.isPlaying && (
          <View style={Styles['taro-video-cover']}>
            <Image
              src={require('../../assets/video/play.png')}
              style={Styles['taro-video-cover-play-button']}
              onClick={this.clickPlayBtn}
            />
            <Text style={Styles['taro-video-cover-duration']}>{duration}</Text>
          </View>
        )}
        {this.props.children}
      </View>
    )
    return (
      <View style={[Styles['taro-video'], this.props.style as Record<string, unknown>]}>
        {videoNode}
      </View>
    )
  }
}

export default _Video

// packages/taro-components/src/components/video/video.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Component, h, ComponentInterface, Prop, State, Event, EventEmitter, Host, Watch, Listen, Element, Method } from '@stencil/core'
import classNames from 'classnames'
import {
  formatTime,
  calcDist,
  normalizeNumber,
  throttle,
  screenFn
} from './utils'

@Component({
  tag: 'taro-video-core',
  styleUrl: './style/index.scss'
})
export class Video implements ComponentInterface {
  private videoRef: HTMLVideoElement
  private controlsRef: HTMLTaroVideoControlElement
  private danmuRef: HTMLTaroVideoDanmuElement
  private toastProgressRef: HTMLDivElement
  private toastProgressTitleRef: HTMLDivElement
  private toastVolumeRef: HTMLDivElement
  private toastVolumeBarRef: HTMLDivElement
  private currentTime = 0
  private lastClickedTime: number
  private lastTouchScreenX: number | undefined
  private lastTouchScreenY: number | undefined
  private isDraggingProgress = false
  private lastVolume: number
  private lastPercentage
  private nextPercentage
  private gestureType = 'none'

  @Element() el: HTMLTaroVideoCoreElement

  /**
   * 要播放视频的资源地址
   */
  @Prop() src: string

  /**
   * 指定视频时长
   */
  @Prop() duration: number

  /**
   * 是否显示默认播放控件（播放/暂停按钮、播放进度、时间）
   */
  @Prop() controls = true

  /**
   * 是否自动播放
   */
  @Prop() autoplay = false

  /**
   * 是否循环播放
   */
  @Prop() loop = false

  /**
   * 是否静音播放
   */
  @Prop() muted = false

  /**
   * 指定视频初始播放位置
   */
  @Prop() initialTime = 0

  /**
   * 视频封面的图片网络资源地址或云文件ID（2.3.0）。若 controls 属性值为 false 则设置 poster 无效
   */
  @Prop() poster: string

  /**
   * 当视频大小与 video 容器大小不一致时，视频的表现形式
   */
  @Prop() objectFit: 'contain' | 'fill' | 'cover' = 'contain'

  /**
   * 若不设置，宽度大于 240 时才会显示
   */
  @Prop() showProgress = true

  /**
   * 是否显示全屏按钮
   */
  @Prop() showFullscreenBtn = true

  /**
   * 是否显示视频底部控制栏的播放按钮
   */
  @Prop() showPlayBtn = true

  /**
   * 是否显示视频中间的播放按钮
   */
  @Prop() showCenterPlayBtn = true

  /**
   * 是否显示静音按钮
   */
  @Prop() showMuteBtn = false

  /**
   * 弹幕列表
   */
  @Prop() danmuList: []

  /**
   * 是否显示弹幕按钮
   */
  @Prop() danmuBtn = false

  /**
   * 是否展示弹幕
   */
  @Prop() enableDanmu = false

  /**
   * 是否开启播放手势，即双击切换播放/暂停
   */
  @Prop() enablePlayGesture = false

  /**
   * 是否开启控制进度的手势
   */
  @Prop() enableProgressGesture = true

  /**
   * 在非全屏模式下，是否开启亮度与音量调节手势
   */
  @Prop() vslideGesture = false

  /**
   * 在全屏模式下，是否开启亮度与音量调节手势
   */
  @Prop() vslideGestureInFullscreen = true

  @State() _duration: number
  @State() _enableDanmu = false
  @State() isPlaying = false
  @State() isFirst = true
  @State() isFullScreen = false
  @State() fullScreenTimestamp = new Date().getTime()
  @State() isMute = false

  @Event({
    eventName: 'play'
  }) onPlay: EventEmitter

  @Event({
    eventName: 'pause'
  }) onPause: EventEmitter

  @Event({
    eventName: 'ended'
  }) onEnded: EventEmitter

  @Event({
    eventName: 'timeupdate'
  }) onTimeUpdate: EventEmitter

  @Event({
    eventName: 'error'
  }) onError: EventEmitter

  @Event({
    eventName: 'fullscreenchange'
  }) onFullScreenChange: EventEmitter

  @Event({
    eventName: 'progress'
  }) onProgress: EventEmitter

  @Event({
    eventName: 'loadedmetadata'
  }) onLoadedMetaData: EventEmitter

  componentWillLoad () {
    this._enableDanmu = this.enableDanmu
  }

  componentDidLoad () {
    if (this.initialTime) {
      this.videoRef.currentTime = this.initialTime
    }
    // 目前只支持 danmuList 初始化弹幕列表，还未支持更新弹幕列表
    this.danmuRef.sendDanmu(this.danmuList)
  }

  componentDidRender () {
  }

  @Watch('enableDanmu')
  watchEnableDanmu (newVal) {
    this._enableDanmu = newVal
  }

  analyseGesture = (e: TouchEvent) => {
    const obj: {
      type: string
      dataX?: number
      dataY?: number
    } = {
      type: 'none'
    }
    const nowX = e.touches[0].screenX
    const nowY = e.touches[0].screenY
    const distX = nowX - (this.lastTouchScreenX as number)
    const distY = nowY - (this.lastTouchScreenY as number)
    const enableVslideGesture = this.isFullScreen ? this.vslideGestureInFullscreen : this.vslideGesture

    if (this.gestureType === 'none') {
      // 两点间距离
      const dist = calcDist(distX, distY)

      // 没有移动
      if (dist < 10) return obj

      if (Math.abs(distY) >= Math.abs(distX)) {
        // 垂直方向移动：调整音量
        if (enableVslideGesture) {
          this.gestureType = 'adjustVolume'
          this.lastVolume = this.videoRef.volume
        } else {
          return obj
        }
      } else if (Math.abs(distY) < Math.abs(distX)) {
        // 水平方向移动：调整进度
        if (this.enableProgressGesture) {
          this.gestureType = 'adjustProgress'
          this.lastPercentage = this.currentTime / (this.duration ?? this._duration)
        } else {
          return obj
        }
      }
    }
    obj.type = this.gestureType
    obj.dataX = normalizeNumber(distX / 200)
    obj.dataY = normalizeNumber(distY / 200)
    return obj
  }

  @Listen('touchmove', {
    target: 'document'
  })
  async onDocumentTouchMove (e: TouchEvent) {
    if (this.lastTouchScreenX === undefined || this.lastTouchScreenY === undefined) return
    if (await this.controlsRef.getIsDraggingProgressBall()) return

    const gestureObj = this.analyseGesture(e)
    if (gestureObj.type === 'adjustVolume') {
      this.toastVolumeRef.style.visibility = 'visible'
      const nextVolume = Math.max(Math.min(this.lastVolume - gestureObj.dataY!, 1), 0)
      this.videoRef.volume = nextVolume
      this.toastVolumeBarRef.style.width = `${nextVolume * 100}%`
    } else if (gestureObj.type === 'adjustProgress') {
      this.isDraggingProgress = true
      this.nextPercentage = Math.max(Math.min(this.lastPercentage + gestureObj.dataX, 1), 0)
      if (this.controls && this.showProgress) {
        this.controlsRef.setProgressBall(this.nextPercentage)
        this.controlsRef.toggleVisibility(true)
      }
      const duration = this.duration || this._duration
      this.toastProgressTitleRef.innerHTML = `${formatTime(this.nextPercentage * duration)} / ${formatTime(duration)}`
      this.toastProgressRef.style.visibility = 'visible'
    }
  }

  @Listen('touchend', {
    target: 'document'
  })
  @Listen('touchcancel', {
    target: 'document'
  })
  onDocumentTouchEnd () {
    if (this.gestureType === 'adjustVolume') {
      this.toastVolumeRef.style.visibility = 'hidden'
    } else if (this.gestureType === 'adjustProgress') {
      this.toastProgressRef.style.visibility = 'hidden'
    }

    if (this.isDraggingProgress) {
      this.isDraggingProgress = false
      this.seek(this.nextPercentage * (this.duration ?? this._duration))
    }

    this.gestureType = 'none'
    this.lastTouchScreenX = undefined
    this.lastTouchScreenY = undefined
  }

  handlePlay = () => {
    this.isPlaying = true
    this.isFirst = false
    this.controlsRef.toggleVisibility(true)
    this.onPlay.emit()
  }

  handlePause = () => {
    this.isPlaying = false
    this.controlsRef.toggleVisibility(true)
    this.onPause.emit()
  }

  handleEnded = () => {
    this.isFirst = true
    this.pause()
    this.controlsRef.toggleVisibility()
    this.onEnded.emit()
  }

  handleTimeUpdate = throttle(async e => {
    this.currentTime = this.videoRef.currentTime
    const duration = this.duration || this._duration

    const isControlDragging = await this.controlsRef.getIsDraggingProgressBall()
    if (this.controls && this.showProgress) {
      if (!isControlDragging && !this.isDraggingProgress) {
        this.controlsRef.setProgressBall(this.currentTime / duration)
        this.controlsRef.setCurrentTime(this.currentTime)
      }
    }

    this.danmuRef.tick(this.currentTime)

    this.onTimeUpdate.emit({
      duration: e.target?.duration,
      currentTime: e.target?.currentTime
    })

    if (this.duration) {
      if (this.currentTime >= this.duration) {
        this.seek(0)
        this.handleEnded()
      }
    }
  }, 250)

  handleError = e => {
    this.onError.emit({
      errMsg: e.target?.error?.message
    })
  }

  handleDurationChange = () => {
    this._duration = this.videoRef.duration
  }

  handleProgress = () => {
    this.onProgress.emit()
  }

  handleLoadedMetaData = (e: Event) => {
    const target = e.target as HTMLVideoElement
    this.onLoadedMetaData.emit({
      width: target.videoWidth,
      height: target.videoHeight,
      duration: target.duration
    })
  }

  /** 播放视频 */
  @Method() async play () {
    this.videoRef.play()
  }

  /** 暂停视频 */
  @Method() async pause () {
    this.videoRef.pause()
  }

  /** 停止视频 */
  @Method() async stop () {
    this.videoRef.pause()
    this.seek(0)
  }

  /** 跳转到指定位置 */
  @Method() async seek (position: number) {
    this.videoRef.currentTime = position
  }

  /** 进入全屏。若有自定义内容需在全屏时展示，需将内容节点放置到 video 节点内。 */
  @Method() async requestFullScreen () {
    this.toggleFullScreen(true)
  }

  /** 退出全屏 */
  @Method() async exitFullScreen () {
    this.toggleFullScreen(false)
  }

  onTouchStartContainer = (e: TouchEvent) => {
    this.lastTouchScreenX = e.touches[0].screenX
    this.lastTouchScreenY = e.touches[0].screenY
  }

  onClickContainer = () => {
    if (this.enablePlayGesture) {
      const now = Date.now()
      if (now - this.lastClickedTime < 300) {
        // 双击
        this.isPlaying ? this.pause() : this.play()
      }
      this.lastClickedTime = now
    }
    this.controlsRef.toggleVisibility()
  }

  onClickFullScreenBtn = (e: MouseEvent) => {
    e.stopPropagation()
    this.toggleFullScreen()
  }

  handleFullScreenChange = e => {
    // 全屏后，"退出"走的是浏览器事件，在此同步状态
    const timestamp = new Date().getTime()
    if (!e.detail && this.isFullScreen && !document[screenFn.fullscreenElement] && timestamp - this.fullScreenTimestamp > 100) {
      this.toggleFullScreen(false)
    }
  }

  @Listen('fullscreenchange') onNativeFullScreenChange (e) {
    this.handleFullScreenChange(e)
  }

  @Listen('webkitfullscreenchange') onWebkitFullScreenChange (e) {
    this.handleFullScreenChange(e)
  }

  @Listen('mozfullscreenchange') onMozFullScreenChange (e) {
    this.handleFullScreenChange(e)
  }

  @Listen('MSFullscreenChange') onMSFullScreenChange (e) {
    this.handleFullScreenChange(e)
  }

  toggleFullScreen = (isFullScreen = !this.isFullScreen) => {
    this.isFullScreen = isFullScreen
    this.controlsRef.toggleVisibility(true)
    this.fullScreenTimestamp = new Date().getTime()
    this.onFullScreenChange.emit({
      fullScreen: this.isFullScreen,
      direction: 'vertical'
    })
    if (this.isFullScreen && !document[screenFn.fullscreenElement]) {
      setTimeout(() => {
        this.videoRef[screenFn.requestFullscreen]({ navigationUI: 'show' })
      }, 0)
    }
  }

  toggleMute = (e: MouseEvent) => {
    e.stopPropagation()
    this.videoRef.muted = !this.isMute
    this.controlsRef.toggleVisibility(true)
    this.isMute = !this.isMute
  }

  toggleDanmu = (e: MouseEvent) => {
    e.stopPropagation()
    this.controlsRef.toggleVisibility(true)
    this._enableDanmu = !this._enableDanmu
  }

  render () {
    const {
      src,
      controls,
      autoplay,
      loop,
      muted,
      poster,
      objectFit,
      isFirst,
      isMute,
      isFullScreen,
      duration,
      _duration,
      showCenterPlayBtn,
      isPlaying,
      _enableDanmu,
      showMuteBtn,
      danmuBtn,
      showFullscreenBtn
    } = this
    const durationTime = formatTime(duration || _duration || null)

    return (
      <Host
        class={classNames('taro-video-container', {
          'taro-video-type-fullscreen': isFullScreen
        })}
        onTouchStart={this.onTouchStartContainer}
        onClick={this.onClickContainer}
      >
        <video
          class='taro-video-video'
          style={{
            'object-fit': objectFit
          }}
          ref={dom => (this.videoRef = dom as HTMLVideoElement)}
          src={src}
          autoplay={autoplay}
          loop={loop}
          muted={muted}
          poster={controls ? poster : undefined}
          playsinline
          webkit-playsinline
          onPlay={this.handlePlay}
          onPause={this.handlePause}
          onEnded={this.handleEnded}
          onTimeUpdate={this.handleTimeUpdate}
          onError={this.handleError}
          onDurationChange={this.handleDurationChange}
          onProgress={this.handleProgress}
          onLoadedMetaData={this.handleLoadedMetaData}
        >
          暂时不支持播放该视频
        </video>

        <taro-video-danmu
          ref={dom => {
            if (dom) {
              this.danmuRef = dom as HTMLTaroVideoDanmuElement
            }
          }}
          enable={_enableDanmu}
        />

        {isFirst && showCenterPlayBtn && !isPlaying && (
          <div class='taro-video-cover'>
            <div class='taro-video-cover-play-button' onClick={() => this.play()} />
            <p class='taro-video-cover-duration'>{durationTime}</p>
          </div>
        )}

        <taro-video-control
          ref={dom => {
            if (dom) {
              this.controlsRef = dom
            }
          }}
          controls={controls}
          currentTime={this.currentTime}
          duration={this.duration || this._duration || undefined}
          isPlaying={this.isPlaying}
          pauseFunc={() => this.pause()}
          playFunc={() => this.play()}
          seekFunc={p => this.seek(p)}
          showPlayBtn={this.showPlayBtn}
          showProgress={this.showProgress}
        >
          {showMuteBtn && (
            <div
              class={classNames('taro-video-mute', {
                'taro-video-type-mute': isMute
              })}
              onClick={this.toggleMute}
            />
          )}
          {danmuBtn && (
            <div
              class={classNames('taro-video-danmu-button', {
                'taro-video-danmu-button-active': _enableDanmu
              })}
              onClick={this.toggleDanmu}>
              弹幕
            </div>
          )}
          {showFullscreenBtn && (
            <div
              class={classNames('taro-video-fullscreen', {
                'taro-video-type-fullscreen': isFullScreen
              })}
              onClick={this.onClickFullScreenBtn}
            />
          )}
        </taro-video-control>

        <div class='taro-video-toast taro-video-toast-volume' ref={dom => {
          if (dom) {
            this.toastVolumeRef = dom
          }
        }}>
          <div class='taro-video-toast-title'>音量</div>
          <div class='taro-video-toast-icon' />
          <div class='taro-video-toast-value'>
            <div class='taro-video-toast-value-content' ref={dom => {
              if (dom) {
                this.toastVolumeBarRef = dom
              }
            }}>
              <div class='taro-video-toast-volume-grids'>
                {Array(10).fill(1).map(() => (
                  <div class='taro-video-toast-volume-grids-item' />
                ))}
              </div>
            </div>
          </div>
        </div>

        <div class='taro-video-toast taro-video-toast-progress' ref={dom => {
          if (dom) {
            this.toastProgressRef = dom
          }
        }}>
          <div class='taro-video-toast-title' ref={dom => {
            if (dom) {
              this.toastProgressTitleRef = dom
            }
          }} />
        </div>
      </Host>
    )
  }
}
