// packages/taro-platform-harmony/src/runtime-framework/react/app.ts
// eslint-disable-next-line import/no-duplicates
import { Current, document } from '@tarojs/runtime'
// eslint-disable-next-line import/no-duplicates
import { eventCenter } from '@tarojs/runtime/dist/runtime.esm'

import { setReconciler } from './connect'
import { injectPageInstance } from './page'
import { EMPTY_OBJ, incrementId, isClassComponent } from './utils'

import type React from 'react'

let h: typeof React.createElement
let ReactDOM

interface IReactMeta {
  PageContext: React.Context<string>
  R: typeof React
  Container: any
}

export const ReactMeta: IReactMeta = {
  R: EMPTY_OBJ,
  Container: EMPTY_OBJ,
  PageContext: EMPTY_OBJ
}

const pageKeyId = incrementId()

export function connectReactPage (
  R: typeof React,
  id: string
) {
  return (Page): React.ComponentClass<any> => {
    // eslint-disable-next-line dot-notation
    const isReactComponent = isClassComponent(R, Page)
    const inject = (node?: any) => node && injectPageInstance(node, id)
    const refs = isReactComponent ? { ref: inject } : {
      forwardedRef: inject,
      // 兼容 react-redux 7.20.1+
      reactReduxForwardedRef: inject
    }

    if (ReactMeta.PageContext === EMPTY_OBJ) {
      ReactMeta.PageContext = R.createContext('')
    }

    return class PageWrapper extends R.Component<any, { hasError: boolean }> {
      state = {
        hasError: false
      }

      static getDerivedStateFromError (error: Error) {
        Current.app?.onError?.(error.message + error.stack)
        return { hasError: true }
      }

      // React 16 uncaught error 会导致整个应用 crash，
      // 目前把错误缩小到页面
      componentDidCatch (error, info: React.ErrorInfo) {
        console.warn(error)
        console.error(info.componentStack)
      }

      render () {
        const children = this.state.hasError
          ? []
          : h(ReactMeta.PageContext.Provider, { value: id }, h(Page, {
            ...this.props,
            ...refs
          }))

        return h(
          'view',
          { id, className: 'taro_page' },
          children
        )
      }
    }
  }
}

export function createReactApp (
  App,
  react,
  dom,
  _config?: any
) {
  ReactMeta.R = react
  h = react.createElement
  ReactDOM = dom
  const appInstanceRef = react.createRef()
  const isReactComponent = isClassComponent(react, App)
  let appWrapper: AppWrapper
  let appWrapperResolver: (value: AppWrapper) => void
  const appWrapperPromise = new Promise<AppWrapper>(resolve => (appWrapperResolver = resolve))

  setReconciler(ReactDOM)

  function getAppInstance (): any {
    return appInstanceRef.current
  }

  function waitAppWrapper (cb: () => void) {
    appWrapper ? cb() : appWrapperPromise.then(() => cb())
  }

  function renderReactRoot () {
    const appId = 'app'

    if (ReactMeta.Container === EMPTY_OBJ) {
      const Container = document.createElement('view')

      Container.id = appId
      ReactMeta.Container = Container
    }

    const root = ReactDOM.createRoot(ReactMeta.Container)
    root.render?.(h(AppWrapper as any))
  }

  class AppWrapper extends react.Component {
    private pages: Array<any> = []
    private elements: Array<any> = []

    constructor (props) {
      super(props)
      appWrapper = this
      appWrapperResolver(this)
    }

    public mount (pageComponent: any, id: string, cb: () => void) {
      const pageWrapper = connectReactPage(react, id)(pageComponent)
      const key = id + pageKeyId()
      const page = () => h(pageWrapper, { key, tid: id })
      this.pages.push(page)
      this.forceUpdate(cb)
    }

    public unmount (id: string, cb: () => void) {
      const elements = this.elements
      const idx = elements.findIndex(item => item.props.tid === id)
      elements.splice(idx, 1)
      this.forceUpdate(cb)
    }

    public render () {
      const { pages, elements } = this

      while (pages.length > 0) {
        const page = pages.pop()!
        elements.push(page())
      }

      let props: React.ComponentProps<any> | null = null

      if (isReactComponent) {
        props = { ref: appInstanceRef }
      }

      return h(
        App,
        props,
        elements.slice()
      )
    }
  }

  renderReactRoot()

  const app = {
    render (cb: () => void) {
      appWrapper.forceUpdate(cb)
    },
    mount (component: any, id: string, cb: () => void) {
      if (appWrapper) {
        appWrapper.mount(component, id, cb)
      } else {
        appWrapperPromise.then(appWrapper => appWrapper.mount(component, id, cb))
      }
    },

    unmount (id: string, cb: () => void) {
      appWrapper?.unmount(id, cb)
    },
    onLaunch (launchParam?: any) {
      waitAppWrapper(() => {
        // 用户编写的入口组件实例
        const app = getAppInstance()
        this.$app = app

        if (app) {
          // 把 App Class 上挂载的额外属性同步到全局 app 对象中
          if (app.taroGlobalData) {
            const globalData = app.taroGlobalData
            const keys = Object.keys(globalData)
            const descriptors = Object.getOwnPropertyDescriptors(globalData)
            keys.forEach(key => {
              Object.defineProperty(this, key, {
                configurable: true,
                enumerable: true,
                get () {
                  return globalData[key]
                },
                set (value) {
                  globalData[key] = value
                }
              })
            })
            Object.defineProperties(this, descriptors)
          }

          app.onCreate?.()
        }
        
        eventCenter.trigger('__taroRouterLaunch', launchParam)
      })
    },
    onShow () {
      waitAppWrapper(() => {
        /**
        * trigger lifecycle
        */
        const app = getAppInstance()
        // class component, componentDidShow
        app?.componentDidShow?.()
      })
    },
    onHide () {
      waitAppWrapper(() => {
        /**
        * trigger lifecycle
        */
        const app = getAppInstance()
        // class component, componentDidShow
        app?.componentDidHide?.()
      })
    }
  }

  // TODO: function componennt hook
  // function triggerAppHook (lifecycle: string, ...option) {
  //   const instance = getPageInstance('taro-app')
  //   if (instance) {
  //     const app = getAppInstance()
  //     const func = hooks.call('getLifecycle', instance, lifecycle)
  //     if (Array.isArray(func)) {
  //       func.forEach(cb => cb.apply(app, option))
  //     }
  //   }
  // }

  Current.app = app

  return app
}

// packages/taro-platform-harmony/src/runtime-framework/solid/app.ts
import { Current, document } from '@tarojs/runtime' // eslint-disable-line import/no-duplicates
import { eventCenter } from '@tarojs/runtime/dist/runtime.esm' // eslint-disable-line import/no-duplicates
import { hooks } from '@tarojs/shared'
import { batch, createContext, createRoot, createSignal, For } from 'solid-js'

import { setReconciler } from './connect'
import { getPageInstance, injectPageInstance } from './page'
import { createComponent, h, render } from './reconciler'
import { EMPTY_OBJ, HOOKS_APP_ID, setDefaultDescriptor, setRouterParams } from './utils'

import type { AppInstance, Instance, PageLifeCycle, PageProps, ReactAppInstance } from '@tarojs/runtime'
import type { AppConfig } from '@tarojs/taro'
import type { Component } from './connect'

export const ReactMeta = {
  R: EMPTY_OBJ,
  Container: EMPTY_OBJ,
  PageContext: EMPTY_OBJ
}

export function createSolidApp(App: Component, config: AppConfig) {
  setReconciler()

  if (ReactMeta.PageContext === EMPTY_OBJ) {
    ReactMeta.PageContext = createContext<string>()
  }

  let appRef: ReactAppInstance
  function getAppInstance(): any {
    return appRef
  }

  function renderReactRoot() {
    const appId = 'app'

    if (ReactMeta.Container === EMPTY_OBJ) {
      const Container = document.createElement('view')

      Container.id = appId
      ReactMeta.Container = Container
    }

    const root = createRoot(() => ReactMeta.Container)
    render(AppWrapper, root)
  }
  const [pages, setPages] = createSignal<any[]>([])
  const [elements, setElements] = createSignal<any[]>([])

  function AppWrapper () {
    appRef = {} as unknown as ReactAppInstance
    return createComponent(App, {
      children: createComponent(For as unknown as Component, {
        get each() {
          return pages()
        },
        children: ({ id, component }) => {
          const children = () =>
            createComponent(ReactMeta.PageContext.Provider as unknown as Component, {
              value: id,
              children: () => {
                injectPageInstance(
                  { id: id, type: 'page' } as unknown as Instance<PageProps>,
                  id
                )
                return createComponent(component, {
                  tid: id,
                })
              },
            })

          return h('root', { id }, children)
        },
      }),
    })
  }

  renderReactRoot()

  const app: AppInstance = Object.create(
    {
      mount(component: Component, id: string, cb: () => void) {
        setPages((old) => [
          ...old,
          { id, component },
        ])
        batch(cb)
      },
      unmount(id: string, cb: () => void) {
        const idx = elements().findIndex((item) => item.id === id)
        setElements((old) => {
          old.splice(idx, 1)
          return old
        })
        batch(cb)
      },
    },
    {
      config: setDefaultDescriptor({
        configurable: true,
        value: config,
      }),

      onLaunch: setDefaultDescriptor({
        value(options) {
          setRouterParams(options)

          const onLaunch = () => {
            const app = getAppInstance()

            if (app) {
              // 把 App Class 上挂载的额外属性同步到全局 app 对象中
              if (app.taroGlobalData) {
                const globalData = app.taroGlobalData
                const keys = Object.keys(globalData)
                const descriptors = Object.getOwnPropertyDescriptors(globalData)
                keys.forEach(key => {
                  Object.defineProperty(this, key, {
                    configurable: true,
                    enumerable: true,
                    get () {
                      return globalData[key]
                    },
                    set (value) {
                      globalData[key] = value
                    }
                  })
                })
                Object.defineProperties(this, descriptors)
              }

              app.onCreate?.()
            }
          }

          onLaunch()
          triggerAppHook('onLaunch', options)
          eventCenter.trigger('__taroRouterLaunch', options)
        },
      }),
      onShow: setDefaultDescriptor({
        value(options) {
          setRouterParams(options)
          triggerAppHook('onShow', options)
        },
      }),
      onHide: setDefaultDescriptor({
        value() {
          triggerAppHook('onHide')
        },
      }),
      onError: setDefaultDescriptor({
        value(error: string) {
          triggerAppHook('onError', error)
        },
      }),
      onPageNotFound: setDefaultDescriptor({
        value(res: unknown) {
          triggerAppHook('onPageNotFound', res)
        },
      }),
    }
  )

  function triggerAppHook(
    lifecycle: keyof PageLifeCycle | keyof AppInstance,
    ...option
  ) {
    const instance = getPageInstance(HOOKS_APP_ID)
    if (instance) {
      const app = getAppInstance()
      const func = hooks.call('getLifecycle', instance, lifecycle)
      if (Array.isArray(func)) {
        func.forEach((cb) => cb.apply(app, option))
      }
    }
  }

  Current.app = app
  return app
}
