// examples/blended-taro-component-vue3/h5/src/pages/index/index.vue
<template>
  <view>
    <view>Detail: </view>
    <button @tap="goto">Go To Detail</button>

    <view>Picker: </view>
    <my-picker title="test" :list="list" :on-button-click="onButtonClick"></my-picker>
  </view>
</template>

<script>
import { ref } from 'vue'
import Taro from '@tarojs/taro'
import Picker from '../../taro/components/picker/index'
import './index.scss'
import '../../taro/css/components/picker/index.css'

export default {
  components: {
    MyPicker: Picker
  },
  setup () {
    const list = ref(['A', 'B', 'C'])

    function goto () {
      Taro.navigateTo({ url: '/pages/detail/index' })
    }

    function onButtonClick () {
      console.log('onButtonClick')
    }

    return {
      list,
      goto,
      onButtonClick
    }
  }
}
</script>

// examples/new-blended/taro-project/src/pages/index/index.jsx
import React, { Component } from 'react'
import { View, Text, Button } from '@tarojs/components'
import Taro from '@tarojs/taro'
import './index.scss'

import Picker from '../../components/picker/index'

export default class Index extends Component {
  render () {
    return (
      <View className='red'>
        <View>Detail: </View>
        <Button onClick={() => Taro.navigateTo({ url: '/taro/pages/detail/index' })}>Go To Detail</Button>
        <View>Picker: </View>
        <Picker 
          title="test" 
          list={['A', 'B', 'C']} 
          onButtonClick={ () => console.log('onclick') } ></Picker>
      </View>
    )
  }
}
